backend:
  name: github
  repo: Hayrizan/rtlc-team
  branch: main

media_folder: "assets/donors"
public_folder: "/rtlc-team/assets/donors"

collections:
  - name: "reviews"
    label: "Отзывы"
    files:
      - name: "approved"
        label: "Отзывы"
        file: "data/reviews.json"
        fields:
          - label: "Отзывы"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Ник", name: "nickname", widget: "string" }
              - { label: "Игра (ID)", name: "project", widget: "string", hint: "Например: endacopia" }
              - { label: "Текст", name: "message", widget: "text" }
              - { label: "Одобрено", name: "approved", widget: "boolean", default: false }
  - name: "donors"
    label: "Топ донатеров"
    files:
      - name: "ranking"
        label: "Рейтинг донатеров"
        file: "data/donors.json"
        fields:
          - label: "Донатеры"
            name: "donors"
            widget: "list"
            summary: "{{fields.name}} — {{fields.amount}} ₽"
            fields:
              - label: "Имя"
                name: "name"
                widget: "string"
              - label: "Сумма доната"
                name: "amount"
                widget: "number"
                value_type: "int"
